name: Workflow-One.
on: [push]

jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
            - name: Echo Job Start
              run: echo "CI starts"
            - name: Install git
              run: |
                echo "Installing git"
               

    Parallel-job:
        runs-on: ubuntu-latest
        steps:
            - name: Running a job in Parallel
              run: echo "This job runs on parallel"
            - name: Stop job
              run: echo " Job done!"
    Dependant-job:
        runs-on: ubuntu-latest
        needs: [CI]
        steps:
            - name: Depend
              run: echo "I depend on CI"
            - name: Multiple shell commands
              run: |
                echo "Hello world"
                sudo apt install apache2
                cd /var/www/html/
                sudo touch index.html
                sudo apt install php
    Clone-Repository:
        runs-on: ubuntu-latest
        steps:
            - name: Check Directory
              run: pwd
            - name: Change Dir
              run: cd /var/www/html/
            - name: Check files in the dir
              run: ls -lrtia
            - name: Initialize git 
              run: sudo git init
            - name: Clone repository
              run: sudo git clone https://github.com/denniskamaa/open-cart.git
            - name: Check files after clone
              run: ls -lrtia


